# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8UzQgwoOiIYSowP0eOVxGJc2xqYMrWR
"""

a = 1202
print("Двоичная", bin(a))
print("Восмерка",oct(a))
print("Дес",a)
print("Шест",hex(a))






a_1 = 45
print(bin(a_1))
print(oct(a_1))
print(hex(a_1))

#task 2
a_2 = 0b1010
b_2 = 0o12
c_2 = 0xa

print(a_2)
print(b_2)
print(c_2)

if cond():
  pypypypypypy

